# Generated by Django 5.0.1 on 2024-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Church_treasurer', 'Church_treasurer'), ('Church_secretary', 'Church_Secretary'), ('District_secretary', 'District_secretary'), ('District_treasurer', 'District_treasurer')], max_length=50),
        ),
    ]
