# Generated by Django 5.0.1 on 2024-02-04 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarter',
            options={'managed': True, 'ordering': ['-start_date'], 'verbose_name_plural': 'quater'},
        ),
        migrations.AddField(
            model_name='quarter',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarter',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarter',
            name='tag',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='AssignedOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='officer_assigned', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_officer', to='accounts.church')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assigned officer',
                'verbose_name_plural': 'assigned officer',
                'db_table': 'assigned_officers',
                'managed': True,
            },
        ),
    ]
