# Generated by Django 5.0.1 on 2024-02-06 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_quarter_options_quarter_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='district',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='assignedofficer',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_church', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Church_treasurer', 'Church_treasurer'), ('Church_secretary', 'Church_secretary'), ('District_secretary', 'District_secretary'), ('District_treasurer', 'District_treasurer')], max_length=50),
        ),
    ]
