# Generated by Django 5.0.1 on 2024-02-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_church_whatsapp_remove_district_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
