# Generated by Django 5.0.1 on 2024-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_district_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
