# Generated by Django 5.0.1 on 2024-02-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_month_end_date_month_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='tag',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1st_Quarter', max_length=2),
        ),
    ]
