# Generated by Django 5.0.1 on 2024-02-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_quarter_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='tag',
            field=models.CharField(choices=[('1st_Quarter', '1st_Quarter'), ('2nd_Quarter', '2nd_Quarter'), ('3rd_Quarter', '3rd_Quarter'), ('4th_Quarter', '4th_Quarter')], default='1st_Quarter', max_length=20),
        ),
    ]
