# Generated by Django 5.0.1 on 2024-02-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_quarter_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedofficer',
            name='assigned_by',
        ),
    ]
