# Generated by Django 5.0.1 on 2024-02-14 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_assignedofficer_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabbath',
            name='sabbath_week_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
