# Generated by Django 5.0.1 on 2024-02-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sabbath_sabbath_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tithe_card_number',
            field=models.IntegerField(default=0),
        ),
    ]
