# Generated by Django 5.0.1 on 2024-02-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_member_tithe_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sabbath',
            old_name='sabbath_date',
            new_name='sabbath_week_ends',
        ),
    ]
