# Generated by Django 5.0.2 on 2024-02-19 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_sabbath_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedofficer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_account_officer', to='accounts.district'),
        ),
        migrations.AlterField(
            model_name='assignedofficer',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_account_officer', to='accounts.church'),
        ),
    ]
