# Generated by Django 5.0.2 on 2024-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_assignedofficer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='tithe_card_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
