# Generated by Django 5.0.2 on 2024-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_quarter_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='phone',
        ),
        migrations.AddField(
            model_name='district',
            name='pastor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='pastors_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
