# Generated by Django 5.0.2 on 2024-02-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_year_quarter_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
