# Generated by Django 5.0.3 on 2024-03-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_year_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_district', to='accounts.district'),
        ),
    ]
