# Generated by Django 5.0.1 on 2024-02-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_sabbath_sabbath_week_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchCashAccount',
            fields=[
                ('cash_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash_generated', models.FloatField()),
                ('cash_spent', models.FloatField()),
                ('cash_to_bank', models.FloatField()),
                ('cash_at_hand', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('sabbath_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
        migrations.CreateModel(
            name='TitheOffering',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.IntegerField()),
                ('tithe', models.CharField(blank=True, max_length=10, null=True)),
                ('offering', models.CharField(blank=True, max_length=10, null=True)),
                ('project', models.CharField(blank=True, max_length=10, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('church_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tithe_offerings', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='TrustFund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('tithe_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('offering_percentage', models.DecimalField(decimal_places=2, default=0.4, max_digits=5)),
                ('tithe_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offering_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_added', models.DateField(auto_now=True)),
                ('sabbath_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('tithe_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offering_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_added', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
                ('sabbath_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchIncome',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('loose_offering', models.CharField(blank=True, max_length=10, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=10, null=True)),
                ('others', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('sabbath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
                ('weekly_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.weeklytransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchExpense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('others', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('weekly_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.weeklytransaction')),
            ],
        ),
    ]
