# Generated by Django 5.0.1 on 2024-02-15 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('accounts', '0011_sabbath_sabbath_week_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountDueDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklytransaction',
            name='member',
        ),
        migrations.AddField(
            model_name='weeklytransaction',
            name='church',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.church'),
        ),
        migrations.AlterField(
            model_name='churchcashaccount',
            name='cash_at_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchcashaccount',
            name='cash_generated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchcashaccount',
            name='cash_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchcashaccount',
            name='cash_to_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchexpense',
            name='others',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='appreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='loose_offering',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='others',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='offering',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='project',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='tithe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TotalToConference',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_remitted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remitance_date', models.DateField()),
                ('date_added', models.DateField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church')),
                ('sabbath_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
    ]
