# Generated by Django 5.0.1 on 2024-02-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_amountduedistrict_remove_weeklytransaction_member_and_more'),
        ('accounts', '0011_sabbath_sabbath_week_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictExpense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.district')),
                ('sabbath_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIncome',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=200)),
                ('offering_from_churches', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('project', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('income_from_churches', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_added', models.DateField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.district')),
                ('sabbath_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
    ]
