# Generated by Django 5.0.1 on 2024-02-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_districtexpense_districtincome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titheoffering',
            name='card_number',
        ),
    ]
