# Generated by Django 5.0.1 on 2024-02-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_titheoffering_sabbath_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchincome',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
