# Generated by Django 5.0.1 on 2024-02-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_titheoffering_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchincome',
            name='appreciation',
        ),
        migrations.RemoveField(
            model_name='churchincome',
            name='loose_offering',
        ),
        migrations.RemoveField(
            model_name='churchincome',
            name='others',
        ),
        migrations.AddField(
            model_name='churchincome',
            name='income_type',
            field=models.CharField(choices=[('APPRECIATION', 'APPRECIATION'), ('DONATION', 'DONATION'), ('CHILD_DEDICATION', 'CHILD_DEDICATION'), ('THANKS_OFFERING', 'THANKS_OFFERING'), ('VOW', 'VOW'), ('SABBATH_SCHOOL', 'SABBATH_SCHOOL'), ('LOOSE_OFFERING', 'LOOSE_OFFERING'), ('13TH_SABBATH', '13TH_SABBATH'), ('HARVESR', 'HARVEST'), ('CAMP_MEETING', 'CAMP_MEETING'), ('AMO', 'AMO'), ('AWM', 'AWM'), ('YOUTH', 'YOUTH'), ('OTHERS', 'OTHERS')], default='DONATION', max_length=20),
        ),
        migrations.AddField(
            model_name='churchincome',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', max_length=10),
        ),
    ]
