# Generated by Django 5.0.1 on 2024-02-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_churchincome_appreciation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchincome',
            name='weekly_transaction',
        ),
        migrations.AddField(
            model_name='churchincome',
            name='offering',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='weeks_offering', to='accounting.weeklytransaction'),
        ),
        migrations.AddField(
            model_name='churchincome',
            name='tithe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='weeks_tithe', to='accounting.weeklytransaction'),
        ),
    ]
