# Generated by Django 5.0.1 on 2024-02-18 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_remove_churchincome_weekly_transaction_and_more'),
        ('accounts', '0013_rename_sabbath_date_sabbath_sabbath_week_ends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustfund',
            name='offering_percentage',
        ),
        migrations.RemoveField(
            model_name='trustfund',
            name='tithe_percentage',
        ),
        migrations.AddField(
            model_name='churchincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CombinedOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_offering', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_calculated', models.DateField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church')),
                ('sabbath_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
    ]
