# Generated by Django 5.0.2 on 2024-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_trustfund_offering_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedoffering',
            name='amount_due_church',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='combinedoffering',
            name='amount_due_conference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='combinedoffering',
            name='amount_due_district',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='payment_method',
            field=models.CharField(choices=[('', ''), ('Cash', 'Cash'), ('Bank', 'Bank')], max_length=10),
        ),
    ]
