# Generated by Django 5.0.2 on 2024-02-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_combinedoffering_amount_due_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titheoffering',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=10),
        ),
    ]
