# Generated by Django 5.0.2 on 2024-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_titheoffering_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchincome',
            name='income_type',
            field=models.CharField(choices=[('', ''), ('APPRECIATION', 'APPRECIATION'), ('DONATION', 'DONATION'), ('CHILD_DEDICATION', 'CHILD_DEDICATION'), ('THANKS_OFFERING', 'THANKS_OFFERING'), ('VOW', 'VOW'), ('SABBATH_SCHOOL', 'SABBATH_SCHOOL'), ('LOOSE_OFFERING', 'LOOSE_OFFERING'), ('13TH_SABBATH', '13TH_SABBATH'), ('HARVESR', 'HARVEST'), ('CAMP_MEETING', 'CAMP_MEETING'), ('AMO', 'AMO'), ('AWM', 'AWM'), ('YOUTH', 'YOUTH'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
    ]
