# Generated by Django 5.0.2 on 2024-02-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_churchincome_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchincome',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=10),
        ),
    ]
