# Generated by Django 5.0.2 on 2024-02-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_churchincome_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchincome',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='weeks_project', to='accounting.weeklytransaction'),
        ),
    ]
