# Generated by Django 5.0.2 on 2024-02-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_churchincome_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchincome',
            name='payment_method',
            field=models.CharField(choices=[('Others', 'Others'), ('Cash', 'Cash'), ('Bank', 'Bank')], max_length=10),
        ),
    ]
