# Generated by Django 5.0.2 on 2024-02-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_churchincome_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchincome',
            name='income_type',
            field=models.CharField(choices=[('APPRECIATION', 'APPRECIATION'), ('DONATION', 'DONATION'), ('CHILD_DEDICATION', 'CHILD_DEDICATION'), ('THANKS_OFFERING', 'THANKS_OFFERING'), ('VOW', 'VOW'), ('SABBATH_SCHOOL', 'SABBATH_SCHOOL'), ('LOOSE_OFFERING', 'LOOSE_OFFERING'), ('13TH_SABBATH', '13TH_SABBATH'), ('HARVESR', 'HARVEST'), ('CAMP_MEETING', 'CAMP_MEETING'), ('AMO', 'AMO'), ('AWM', 'AWM'), ('YOUTH', 'YOUTH'), ('OTHERS', 'OTHERS'), ('T_O_P', 'T_O_P')], max_length=20),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='offering',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks_offering', to='accounting.weeklytransaction'),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='project',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks_project', to='accounting.weeklytransaction'),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='tithe',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks_tithe', to='accounting.weeklytransaction'),
        ),
    ]
