# Generated by Django 5.0.2 on 2024-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_churchincome_offering_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchexpense',
            old_name='others',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='churchexpense',
            name='weekly_transaction',
        ),
        migrations.AddField(
            model_name='churchexpense',
            name='title',
            field=models.CharField(default='expense', max_length=255),
        ),
    ]
