# Generated by Django 5.0.2 on 2024-02-21 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_churchcashaccount_church_churchexpense_church_and_more'),
        ('accounts', '0016_alter_member_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaltoconference',
            name='church',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.church'),
        ),
    ]
