# Generated by Django 5.0.2 on 2024-02-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_delete_amountduedistrict_trustfund_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedoffering',
            name='total_available_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='income_type',
            field=models.CharField(choices=[('APPRECIATION', 'APPRECIATION'), ('DONATION', 'DONATION'), ('CHILD_DEDICATION', 'CHILD_DEDICATION'), ('THANKS_OFFERING', 'THANKS_OFFERING'), ('VOW', 'VOW'), ('SABBATH_SCHOOL', 'SABBATH_SCHOOL'), ('LOOSE_OFFERING', 'LOOSE_OFFERING'), ('13TH_SABBATH', '13TH_SABBATH'), ('HARVEST', 'HARVEST'), ('CAMP_MEETING', 'CAMP_MEETING'), ('AMO', 'AMO'), ('AWM', 'AWM'), ('YOUTH', 'YOUTH'), ('OTHERS', 'OTHERS'), ('T_O_P', 'T_O_P')], max_length=20),
        ),
    ]
