# Generated by Django 5.0.2 on 2024-02-21 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_combinedoffering_total_available_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustfund',
            name='offering_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_due_conference', to='accounting.combinedoffering'),
        ),
        migrations.AlterField(
            model_name='trustfund',
            name='tithe_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_weekly_tithe', to='accounting.weeklytransaction'),
        ),
    ]
