# Generated by Django 5.0.2 on 2024-02-21 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_alter_trustfund_offering_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtincome',
            old_name='donation',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='districtincome',
            old_name='particulars',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='districtexpense',
            name='particulars',
        ),
        migrations.RemoveField(
            model_name='districtincome',
            name='income_from_churches',
        ),
        migrations.RemoveField(
            model_name='districtincome',
            name='offering_from_churches',
        ),
        migrations.RemoveField(
            model_name='districtincome',
            name='project',
        ),
        migrations.RemoveField(
            model_name='districtincome',
            name='vow',
        ),
        migrations.AddField(
            model_name='districtexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='districtexpense',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='districtexpense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='districtexpense',
            name='title',
            field=models.CharField(default='expense', max_length=255),
        ),
        migrations.AddField(
            model_name='districtincome',
            name='income_type',
            field=models.CharField(choices=[('DONATION', 'DONATION'), ('VOW', 'VOW'), ('OFFERING_fROM_CHURCHES', 'OFFERING_fROM_CHURCHES'), ('PROJECT', 'PROJECT'), ('OTHERS', 'OTHERS')], default='DONATION', max_length=30),
        ),
        migrations.AddField(
            model_name='districtincome',
            name='payment_method',
            field=models.CharField(choices=[('Others', 'Others'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='CASH', max_length=10),
        ),
    ]
