# Generated by Django 5.0.2 on 2024-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_rename_donation_districtincome_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titheoffering',
            name='offering',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='project',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='tithe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
