# Generated by Django 5.0.2 on 2024-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_titheoffering_offering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titheoffering',
            name='offering',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='project',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='titheoffering',
            name='tithe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
