# Generated by Django 5.0.2 on 2024-02-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_remove_churchincome_offering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchincome',
            name='Weekly_transaction',
        ),
        migrations.AddField(
            model_name='churchincome',
            name='offering',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks_offering', to='accounting.weeklytransaction'),
        ),
        migrations.AddField(
            model_name='churchincome',
            name='project',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks_project', to='accounting.weeklytransaction'),
        ),
        migrations.AddField(
            model_name='churchincome',
            name='tithe',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks_tithe', to='accounting.weeklytransaction'),
        ),
    ]
