# Generated by Django 5.0.2 on 2024-02-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_remove_churchincome_weekly_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchincome',
            name='offering',
        ),
        migrations.RemoveField(
            model_name='churchincome',
            name='project',
        ),
        migrations.RemoveField(
            model_name='churchincome',
            name='tithe',
        ),
        migrations.AddField(
            model_name='churchincome',
            name='Weekly_transaction',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks_income_sum', to='accounting.weeklytransaction'),
        ),
    ]
