# Generated by Django 5.0.2 on 2024-02-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_churchexpense_weekly_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtincome',
            name='tithe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tithe_from_church', to='accounting.combinedoffering'),
        ),
    ]
