# Generated by Django 5.0.2 on 2024-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_alter_districtincome_tithe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtincome',
            name='income_type',
            field=models.CharField(choices=[('DONATION', 'DONATION'), ('VOW', 'VOW'), ('OFFERING_fROM_CHURCHES', 'OFFERING_fROM_CHURCHES'), ('PROJECT', 'PROJECT'), ('OTHERS', 'OTHERS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='districtincome',
            name='payment_method',
            field=models.CharField(choices=[('Others', 'Others'), ('Cash', 'Cash'), ('Bank', 'Bank')], max_length=10),
        ),
    ]
