# Generated by Django 5.0.2 on 2024-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_districtincome_income_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
