# Generated by Django 5.0.2 on 2024-03-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_alter_districtincome_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchexpense',
            name='Weekly_transaction',
        ),
        migrations.RemoveField(
            model_name='churchincome',
            name='Weekly_transaction',
        ),
    ]
