# Generated by Django 5.0.2 on 2024-03-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_remove_churchexpense_weekly_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtincome',
            old_name='tithe',
            new_name='offering',
        ),
        migrations.AlterField(
            model_name='districtincome',
            name='income_type',
            field=models.CharField(choices=[('DONATION', 'DONATION'), ('VOW', 'VOW'), ('OFFERING_FROM_CHURCHES', 'OFFERING_FROM_CHURCHES'), ('PROJECT', 'PROJECT'), ('OTHERS', 'OTHERS')], max_length=30),
        ),
    ]
