# Generated by Django 5.0.2 on 2024-03-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_rename_tithe_districtincome_offering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtincome',
            name='offering',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offering_from_church', to='accounting.combinedoffering'),
        ),
    ]
