# Generated by Django 5.0.2 on 2024-03-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_alter_districtincome_offering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtincome',
            name='offering',
        ),
    ]
