# Generated by Django 5.0.2 on 2024-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_remove_districtincome_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchexpense',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
