# Generated by Django 5.0.3 on 2024-03-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_alter_churchcashaccount_cash_at_hand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combinedoffering',
            old_name='church',
            new_name='associated_church',
        ),
    ]
