# Generated by Django 4.2.7 on 2024-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_rename_church_combinedoffering_associated_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustfund',
            name='offering_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trustfund',
            name='tithe_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
