# Generated by Django 5.0.3 on 2024-03-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_alter_trustfund_offering_amount_and_more'),
        ('accounts', '0020_year_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchcashaccount',
            name='cash_generated',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churchcashaccount',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church'),
        ),
        migrations.AlterField(
            model_name='churchexpense',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church'),
        ),
        migrations.AlterField(
            model_name='churchexpense',
            name='sabbath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath'),
        ),
        migrations.AlterField(
            model_name='churchincome',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church'),
        ),
    ]
