# Generated by Django 5.0.3 on 2024-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_alter_churchcashaccount_cash_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchcashaccount',
            name='balance_bf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
