# Generated by Django 5.0.3 on 2024-03-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_churchcashaccount_balance_bf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchcashaccount',
            name='balance_bf',
        ),
    ]
