# Generated by Django 5.0.3 on 2024-03-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_remove_churchcashaccount_balance_bf'),
        ('accounts', '0020_year_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceBroughtForward',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.church')),
                ('sabbath_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath')),
            ],
        ),
    ]
