# Generated by Django 5.0.3 on 2024-03-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_balancebroughtforward'),
        ('accounts', '0020_year_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancebroughtforward',
            options={'ordering': ['sabbath_week', 'church']},
        ),
        migrations.AlterField(
            model_name='balancebroughtforward',
            name='sabbath_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sabbath'),
        ),
    ]
