# Generated by Django 5.0.3 on 2024-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_alter_churchincome_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchincome',
            name='income_type',
            field=models.CharField(choices=[('APPRECIATION', 'APPRECIATION'), ('DONATION', 'DONATION'), ('CHILD_DEDICATION', 'CHILD_DEDICATION'), ('THANKS_OFFERING', 'THANKS_OFFERING'), ('VOW', 'VOW'), ('SABBATH_SCHOOL_EXPENSE_OFFERING', 'SABBATH_SCHOOL_EXPENSE_OFFERING'), ('SABBATH_SCHOOL_OFFERING', 'SABBATH_SCHOOL_OFFERING'), ('LOOSE_OFFERING', 'LOOSE_OFFERING'), ('ENVELOPE_OFFERING', 'LOOSE_ENVELOPE'), ('13TH_SABBATH', '13TH_SABBATH'), ('HARVEST', 'HARVEST'), ('CAMP_MEETING', 'CAMP_MEETING'), ('AMO', 'AMO'), ('AWM', 'AWM'), ('YOUTH', 'YOUTH'), ('OTHERS', 'OTHERS'), ('T_O_P', 'T_O_P')], max_length=40),
        ),
    ]
